spring.application.name=springboot-webflux-rest
spring.mongodb.uri=mongodb+srv://cristian:${MONGO_PASSWORD}@cluster0.5urqg.mongodb.net/springboot_webflux?appName=Cluster0
server.port=8081
api.reset.secret=${RESET_SECRET}